// This file is generated by Sim IDX. Do not edit manually.
import { pgEnum, pgTable as table } from "drizzle-orm/pg-core";
import * as t from "drizzle-orm/pg-core";
import { db, types } from "@duneanalytics/sim-idx";

export const punkBought = table("punk_bought", {
  blockTimestamp: db.uint256('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  punkIndex: db.uint256('punk_index'),
  value: db.uint256('value'),
  fromAddress: db.address('from_address'),
  toAddress: db.address('to_address'),
})

export const punkClaimed = table("punk_claimed", {
  blockTimestamp: db.uint256('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  punkIndex: db.uint256('punk_index'),
  toAddress: db.address('to_address'),
})

export const punkOffered = table("punk_offered", {
  blockTimestamp: db.uint256('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  punkIndex: db.uint256('punk_index'),
  minValue: db.uint256('min_value'),
  toAddress: db.address('to_address'),
})

export const punkTransfer = table("punk_transfer", {
  blockTimestamp: db.uint256('block_timestamp'),
  txnHash: db.bytes32('txn_hash'),
  blockNumber: db.uint256('block_number'),
  punkIndex: db.uint256('punk_index'),
  fromAddress: db.address('from_address'),
  toAddress: db.address('to_address'),
})

export const punkSvgAndAttributes = table("punk_svg_and_attributes", {
  punkIndex: db.uint256('punk_index'),
  svg: t.text('svg'),
  attributes: t.text('attributes'),
})
